# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :R1 => {
        :box_name => "centos/7",
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "lan21"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: "lan31"},
                   {adapter: 4, auto_config: false, virtualbox__intnet: "area1"},
                ]
  },
:R2 => {
        :box_name => "centos/7",
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "lan21"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: "lan32"},
                   {adapter: 4, auto_config: false, virtualbox__intnet: "lan42"},
                   {adapter: 5, auto_config: false, virtualbox__intnet: "area2"},
                ]
  },
:R3 => {
        :box_name => "centos/7",
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "lan31"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: "lan32"},
                   {adapter: 4, auto_config: false, virtualbox__intnet: "lan43"},
                   {adapter: 5, auto_config: false, virtualbox__intnet: "area3"},
                ]
  },
  :R4 => {
        :box_name => "centos/7",
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "lan43"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: "lan42"},
                   {adapter: 4, auto_config: false, virtualbox__intnet: "area4"},
                ]
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "R1"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "net.ipv4.ip_forward = 1" > /etc/sysctl.conf
            echo "net.ipv4.conf.all.rp_filter=2" >> /etc/sysctl.conf
            sysctl -p /etc/sysctl.conf
            yum install -y quagga
            cp /usr/share/doc/quagga-0.99.22.4/zebra.conf.sample /etc/quagga/zebra.conf
            cp /usr/share/doc/quagga-0.99.22.4/ospfd.conf.sample /etc/quagga/ospfd.conf
            chown quagga:quaggavt /etc/quagga/ospfd.conf
            systemctl start zebra
            systemctl start ospfd
            SHELL
        when "R2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "net.ipv4.ip_forward = 1" > /etc/sysctl.conf
            echo "net.ipv4.conf.all.rp_filter=2" >> /etc/sysctl.conf
            sysctl -p /etc/sysctl.conf
            yum install -y quagga
            cp /usr/share/doc/quagga-0.99.22.4/zebra.conf.sample /etc/quagga/zebra.conf
            cp /usr/share/doc/quagga-0.99.22.4/ospfd.conf.sample /etc/quagga/ospfd.conf
            chown quagga:quaggavt /etc/quagga/ospfd.conf
            systemctl start zebra
            systemctl start ospfd
            SHELL
        when "R3"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "net.ipv4.ip_forward = 1" > /etc/sysctl.conf
            echo "net.ipv4.conf.all.rp_filter=2" >> /etc/sysctl.conf
            sysctl -p /etc/sysctl.conf
            yum install -y quagga
            cp /usr/share/doc/quagga-0.99.22.4/zebra.conf.sample /etc/quagga/zebra.conf
            cp /usr/share/doc/quagga-0.99.22.4/ospfd.conf.sample /etc/quagga/ospfd.conf
            chown quagga:quaggavt /etc/quagga/ospfd.conf
            chown quagga:quaggavt /etc/quagga/ospfd.conf
            systemctl start zebra
            systemctl start ospfd
            SHELL
        when "R4"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "net.ipv4.ip_forward = 1" > /etc/sysctl.conf
            echo "net.ipv4.conf.all.rp_filter=2" >> /etc/sysctl.conf
            sysctl -p /etc/sysctl.conf
            yum install -y quagga
            cp /usr/share/doc/quagga-0.99.22.4/zebra.conf.sample /etc/quagga/zebra.conf
            cp /usr/share/doc/quagga-0.99.22.4/ospfd.conf.sample /etc/quagga/ospfd.conf
            chown quagga:quaggavt /etc/quagga/ospfd.conf
            systemctl start zebra
            systemctl start ospfd
            SHELL
        end

      end

  end
  
  
end
