#! /bin/bash
#Процесс копирования на диск
echo Выполняется процесс копирования с высоким приоритетом...
ionice -c1 -n1 dd if=/dev/urandom of=/tmp/file1 bs=1M count=1024
echo ------------------------------------------
echo Выполняется процесс копирования с низким приоритетом...
ionice -c3 -n7 dd if=/dev/urandom of=/tmp/file2 bs=1M count=1024
echo Выполнение всех процесов завершено
exit 0
